### PR TITLE
Updating Openshift w/ 1.0.0.BETA2

### PR DESCRIPTION
**Pull request by matzew**
As discussed, Version `0.13.0` will contain beta2 of the UPS.
# How to test ?

Have `rhc` installed and run:

```
rhc app create --no-git <APP> https://cartreflect-claytondev.rhcloud.com/reflect?github=matzew/openshift-origin-cartridge-aerogear-push&commit=9fa82b37cea38cbc0f2449c60e42bc7bb2cb988c
```

on you shell (replace the <APP> with a name you like)

### CODE REVIEW

**Comment by matzew** [comment]
@danbev I kept the SimplePush Server at version 0.11

@qmx @secondsun @fjuma please review

**Comment by fjuma** [comment]
@matzew Looks good to me.

**Comment by danbev** [comment]
sounds good!

fredag 15 augusti 2014 skrev Matthias Wessendorf notifications@github.com:

**Comment by secondsun** [comment]
Don't the shell files and xml files need license headers?

**Comment by matzew** [comment]
Oh, right I can update that!

Or is that a problem @fjuma? Any general Openshift rule/policy here?

On Friday, August 15, 2014, Hoyt Summers Pittman notifications@github.com
wrote:

> Don't the shell files and xml files need license headers?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/20#issuecomment-52327389
> .

## 

Sent from Gmail Mobile

**Comment by secondsun** [comment]
Minus license, it deploys, it pushes, it works for Android.  Unles there is
anything else :+1:

Summers Pittman

> > Phone:404 941 4698
> > Java is my crack.

**Comment by fjuma** [comment]
@matzew The corresponding AS 7 files don't include license headers (e.g., see https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-jbossas/versions/7/bin/standalone.sh, https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-jbossas/versions/7/standalone/configuration/standalone.xml, etc.)

**Comment by matzew** [comment]
works for me

On Friday, August 15, 2014, Farah Juma notifications@github.com wrote:

> @matzew https://github.com/matzew The corresponding AS 7 files don't
> include license headers (e.g., see
> https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-jbossas/versions/7/bin/standalone.sh,
> 
> https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-jbossas/versions/7/bin/standalone.sh,
> etc.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/20#issuecomment-52332278
> .

## 

Sent from Gmail Mobile

**Comment by abstractj** [comment]
@matzew after the removal of license headers mentioned by @secondsun, I can merge it.

**Comment by matzew** [comment]
@abstractj did that. I think @qmx wants to review/test as well

**Comment by matzew** [comment]
Rebased on latest master!

**Pull request merged**
