### PR TITLE
1.0.0.Final of UnifiedPush Server + deleting old versions

### PR DESCRIPTION
**Pull request by matzew**
As discussed we delete old versions and keep `0.13.0` (contain beta2 of the UPS)

As well discussed, the `1.0.0` contains the final of the UnifiedPush Server.
# How to test ?

Have rhc installed and run:

```
rhc app create --no-git <APP> https://cartreflect-claytondev.rhcloud.com/reflect?github=matzew/openshift-origin-cartridge-aerogear-push&commit=f00f5d3df22b4a6f9116a37fa90f28f533a6db86
```

on you shell (replace the with a name you like)

### CODE REVIEW

**Comment by matzew** [comment]
_DO NOT YET MERGE_

this should be merged, after the WAR files for 1.0.0.Final hit Maven Central

**Comment by matzew** [comment]
@danbev I kept the SimplePush Server at version 0.11

@qmx @secondsun @fjuma please review

**Comment by fjuma** [comment]
Looks good to me.

**Comment by secondsun** [comment]
It deploys to openshift and I can log in.  Is there anything else I should look for?

**Comment by matzew** [comment]
create an empty app ? :)  but that's really it! thanks for testing!

On Fri, Aug 22, 2014 at 4:53 PM, Hoyt Summers Pittman <
notifications@github.com> wrote:

> It deploys to openshift and I can log in. Is there anything else I should
> look for?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/23#issuecomment-53070094
> .

## 

Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by secondsun** [comment]
:+1:

**Comment by matzew** [comment]
:heart:

**Comment by abstractj** [comment]
@matzew testing.... :running:

**Comment by abstractj** [comment]
@matzew tested against golum https://golum-abstractj.rhcloud.com/ag-push on my Galaxy, works like a charm

+1

**Comment by matzew** [comment]
cool! :-)

On Fri, Aug 22, 2014 at 5:45 PM, Bruno Oliveira notifications@github.com
wrote:

> @matzew https://github.com/matzew tested against golum
> https://golum-abstractj.rhcloud.com/ag-push on my Galaxy, works like a
> charm
> 
> +1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/23#issuecomment-53077374
> .

## 

Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Pull request merged**
