### PR TITLE
Add mysql cartridge requirement

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by fjuma** [comment]
Merged. Thanks, Ben!

**Comment by fjuma** [comment]
@bparees Just noticed that now, when the MySQL cartridge isn't specified in the creation command, it will automatically get added in a separate gear instead of in the same gear as the aerogear-push cartridge. Is there a way to fix that?

**Comment by bparees** [comment]
@fjuma this behavior will be fixed in the next couple days when Online gets updated w/ the latest release.

**Comment by fjuma** [comment]
@bparees Perfect, I'll keep an eye out for it and then re-add this change. Thanks!

**Pull request merged**
