### PR TITLE
WIP Node Platform - remove lsof usage

### PR DESCRIPTION
**Pull request by jwhonce**
@qmx or @fjuma Please test and merge at your earliest convenience.  You may email any questions to jhonce at redhat dot com.  Thanks.

### CODE REVIEW

**Comment by fjuma** [comment]
Tested and merged. Thanks, Jhon!

**Comment by matzew** [comment]
@fjuma do we need this here too ? 

https://github.com/aerogear/openshift-origin-cartridge-aerogear-push-wildfly/blob/master/bin/control#L159

**Comment by fjuma** [comment]
@matzew Yes, we should fix it there, too.

**Comment by fjuma** [comment]
@matzew https://github.com/aerogear/openshift-origin-cartridge-aerogear-push-wildfly/pull/1

**Pull request merged**
