### PR TITLE
Updating SimplePush Server to 0.12.1

### PR DESCRIPTION
**Pull request by danbev**
A running instance of SimplePush can be found at [sps121-dbevenius.rhcloud.com](http://sps121-dbevenius.rhcloud.com:8000/simplepush/info)

### CODE REVIEW

**Comment by danbev** [comment]
@matzew Would you mind doing a review?

**Comment by matzew** [comment]
Tested with:
- http://people.apache.org/~matzew/ws_test.html
- http://people.apache.org/~matzew/sockjs-client.html

:+1:

**Comment by matzew** [comment]
@lfryc mind to check this PR ?

**Comment by matzew** [comment]
is this ready to merge? @danbev @lfryc

**Comment by danbev** [comment]
@matzew All clear from my end.

**Comment by matzew** [comment]
landed!

On Thu, Nov 20, 2014 at 7:14 AM, Daniel Bevenius notifications@github.com
wrote:

> @matzew https://github.com/matzew All clear from my end.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/26#issuecomment-63765771
> .

## 

Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Pull request merged**
