### PR TITLE
put http port back in place

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
jboss itself still needs to listen on 8080/http because we do ssl termination.  tohttps just forces the proxy to redirect the user to https during the request into the proxy, it doesn't affect the transport to the gear itself.

**Comment by bparees** [comment]
@fjuma @matzew merge please.

**Comment by bparees** [comment]
@vibe13 fyi.

**Comment by fjuma** [comment]
Merged. Thanks @bparees!

**Comment by matzew** [comment]
@lfryc @vibe13 

based on https://github.com/bparees/openshift-origin-cartridge-aerogear-push/commit/84e7f0f174939dabe264e022b44402626f5e35c9#diff-82f2887ff90e8f37cbe0ba196311d532

@fjuma and @bparees merged (and submitted) this PR

**Pull request merged**
