### PR TITLE
Version 0.11 (containing UPS 0.11)

### PR DESCRIPTION
**Pull request by matzew**
Adding two WARs:
- auth.war (custom Keycloak auth server)
- ag-push.war (UnifiedPush Server)

No more "ROOT.war" 

Tweaking HSTS via standalone.xml: 
https://github.com/matzew/openshift-origin-cartridge-aerogear-push/blob/e2a8a0b6ade78f9e3c58abb37a0f9b9e659c991d/versions/0.11.0/standalone/configuration/standalone.xml#L519

Want to test it  ? 

```
rhc app create --no-git <APP> https://cartreflect-claytondev.rhcloud.com/reflect?github=matzew/openshift-origin-cartridge-aerogear-push
```

Afterwards go to "SERVER/ag-push" (note the `/ag-push`)

### CODE REVIEW

**Comment by danbev** [comment]
I just noticed the duplicated SimplePush jars which existed before this PR
but I'd like clean this up. I'll create a PR for this. Sorry for causing a
delay here.

måndag 7 juli 2014 skrev Matthias Wessendorf notifications@github.com:

**Comment by matzew** [comment]
there is no delay here at all :-)

thanks for helping on the clean-up!

On Mon, Jul 7, 2014 at 5:25 PM, Daniel Bevenius notifications@github.com
wrote:

> I just noticed the duplicated SimplePush jars which existed before this PR
> but I'd like clean this up. I'll create a PR for this. Sorry for causing a
> delay here.
> 
> måndag 7 juli 2014 skrev Matthias Wessendorf notifications@github.com:
> 
> > Adding two WARs:
> > - auth.war (custom Keycloak auth server)
> > - ag-push.war (UnifiedPush Server)
> > 
> > No more "ROOT.war"
> > 
> > Tweaking HSTS via standalone.xml:
> > 
> > ## https://github.com/matzew/openshift-origin-cartridge-aerogear-push/blob/e2a8a0b6ade78f9e3c58abb37a0f9b9e659c991d/versions/0.11.0/standalone/configuration/standalone.xml#L519
> > 
> > You can merge this Pull Request by running
> > 
> > git pull
> > https://github.com/matzew/openshift-origin-cartridge-aerogear-push master
> > 
> > Or view, comment on, or merge it at:
> > 
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16
> > Commit Summary
> > - Adding version 0.11; adding UPS and auth server
> > - lets use mysql-5.5
> > 
> > File Changes
> > - _M_ README.md
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-0>
> > 
> > (2)
> > - _M_ bin/install
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-1>
> > 
> > (8)
> > - _M_ metadata/managed_files.yml
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-2>
> > 
> > (6)
> > - _M_ metadata/manifest.yml
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-3>
> > 
> > (4)
> > - _A_ versions/0.11.0/bin/standalone.conf
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-4>
> > 
> > (123)
> > - _A_ versions/0.11.0/bin/standalone.sh
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-5>
> > 
> > (237)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-crypto-0.1.2.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-6>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-netty-codec-sockjs-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-7>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-netty-codec-sockjs-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-8>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-netty-codec-sockjs-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-9>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-common-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-10>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-common-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-11>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-common-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-12>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-couchdb-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-13>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-couchdb-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-14>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-couchdb-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-15>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-in-memory-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-16>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-in-memory-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-17>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-in-memory-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-18>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-jpa-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-19>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-jpa-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-20>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-jpa-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-21>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-redis-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-22>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-redis-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-23>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-datastore-redis-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-24>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-protocol-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-25>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-protocol-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-26>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-protocol-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-27>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-api-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-28>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-api-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-29>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-api-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-30>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-core-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-31>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-core-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-32>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-core-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-33>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-netty-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-34>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-netty-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-35>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-netty-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-36>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-wildfly-0.10.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-37>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-wildfly-0.10.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-38>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/aerogear-simplepush-server-wildfly-0.11.0-SNAPSHOT.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-39>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/bcprov-jdk16-140.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-40>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/commons-codec-1.6.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-41>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/commons-io-2.0.1.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-42>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/commons-logging-1.1.1.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-43>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/commons-pool-1.5.5.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-44>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/httpclient-4.2.5.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-45>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/httpclient-cache-4.2.5.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-46>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/httpcore-4.2.4.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-47>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/jackson-annotations-2.3.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-48>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/jackson-core-2.3.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-49>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/jackson-databind-2.3.0.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-50>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/jedis-2.0.0.jar
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-51>
> > 
> > (0)
> > - _A_
> >   versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/module.xml
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-52>
> > 
> > (76)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/netty-all-5.0.0.Alpha1.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-53>
> > 
> > (0)
> > - _A_
> > 
> > versions/0.11.0/modules/org/jboss/aerogear/simplepush/main/org.ektorp-1.4.1.jar
> > 
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-54>
> > 
> > (0)
> > - _A_ versions/0.11.0/standalone/configuration/logging.properties
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-55>
> > 
> > (52)
> > - _A_ versions/0.11.0/standalone/configuration/settings.base.xml
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-56>
> > 
> > (2)
> > - _A_ versions/0.11.0/standalone/configuration/settings.rhcloud.xml
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-57>
> > 
> > (33)
> > - _A_ versions/0.11.0/standalone/configuration/standalone.xml
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-58>
> > 
> > (574)
> > - _A_ versions/0.11.0/standalone/deployments/ag-push.war
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-59>
> > 
> > (0)
> > - _A_ versions/0.11.0/standalone/deployments/auth-server.war
> >   <
> >   https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16/files#diff-60>
> > 
> > (0)
> > 
> > Patch Links:
> > 
> > ## 
> > 
> > ## https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16.patch
> > 
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aerogear/openshift-origin-cartridge-aerogear-push/pull/16#issuecomment-48193424
> .

## 

Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by sebastienblanc** [comment]
Tested on my side : 
- OpenShift instance creation :+1: 
- Create a push app + android variant :+1: 
- Device registration :+1: 
- Sending Push Notification :+1:

**Comment by danbev** [comment]
:+1: Looks good

**Pull request merged**
